server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://159.75.211.245:3306/floor_shop
    username: pwh
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mail:
    host: smtp.qq.com
    port: 587
    username: 2145865322@qq.com
    protocol: smtp
    default-encoding: UTF-8
    password: kfofchisahhjijii

jwt:
  config:
    key: tong
    ttl: 36000000000000
mybatis-plus:
  type-aliases-package: com.example.floor_myshop.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.example.floor_myshop.mapper: debug
