server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://159.75.211.245:3306/floor_shop
    username: pwh
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
